#+TITLE: Egypt1967
بالذمة لو كان حكام مصر في العهد الناصري عبارة عن شبكة من الموساد فهل كانوا سيفعلون أكثر من ذلك؟!
العوامل المباشرة لهزيمة مصر في 1967:
المصادر: معلومات مستخلصة من مذكرات قادة النظام الناصري السياسية والعسكرية.
- الامتناع عن تجنيد المتعلمين إلا في أضيق الحدود خوفا من انتشار معارضة سياسية في الجيش.
- هسهس الأمن والخوف من حدوث انقلاب عسكري سيطر على القيادة السياسية والعسكرية، وقد انعكس هذا على توزيع المناصب والصلاحيات داخل الجيش.
- القوات البحرية والجوية مستقلة عن رئاسة الأركان.
- تم إهمال القوات الجوية (تخفيض ساعات الطيران عام 1966-  67 وعدم إقامة دشم للطائرات..إلخ)، وضعف وسائل الدفاع الجوي عن المطارات.. إلخ.
-  تم تخفيض الميزانية العسكرية عام 1966-  1967 بسبب الأزمة الاقتصادية وإفلاس البلاد. وكانت اعتمادات الجيش عام 1967 تكفي المرتبات والمصاريف العادية فقط .
- القيادة السياسية علمت يقينا أن الحشود الإسرائيلية على سوريا كانت مجرد سراب ومع ذلك أصرت على الحشد واستفزاز إسرائيل بشكل يثير الشك وهي تعلم يقينا أنها غير جاهزة للحرب وصرح عبد الناصر بهذا مرات.
-  رفضت القيادة السياسية القيام بالضربة الأولى دون أن تستعد للرد على الضربة الإسرائيلية المتوقعة.
-  نظم اتصالات عتيقة وفي حالة يرثى لها حتى إن القوات التي هوجمت بريا مبكرا في سيناء (قبل الهجوم الجوي الشامل) قد أبلغت القيادة بعد الهجوم بساعة (ولم يهتم أحد بهذا الهجوم حتى بعد العلم به!).
-  ضعف صيانة الأسلحة.
-  كثرة إجازات الضباط وقلة ساعات التدريب.
-  لا مناورات منذ 1954.
- كان يوجد منصب وزير الحربية، ورئيس الأركان، والقائد العام للجيش، بالإضافة إلى القائد الأعلى للقوات المسلحة، مع تداخل الوظائف السياسية مع العسكرية.
- لم يكن الضباط الكبار يعرفون أن الدبابات تستطيع أن تمشي في الرمال ففوجئوا بالدبابات الإسرائيلية تأتيهم من حيث لا يتوقعون.
- إشارتا عجلون الشهيرتان من الأردن تفيدان ببدء الهجوم الجوي الإسرائيلي: جندي الإشارة في مصر رفض أن يوقظ شمس بدران وزير الحربية ليسلمه الإشارة الأولى الواضحة – غياب ضابط المناوبة وذهابه للنوم في بيته – تغيير تردد الإشارة في غرفة عمليات القوات الجوية في موعدها أدى إلى عدم استقبال الإشارة الثانية.
-  طائرة المشير وبعض الوزراء السوريين والعراقيين في الجو بأمر من عبد الناصر ووقف عمل مضادات الطيران بهذه الحجة بأمر محمد فوزي (هذا الشخص عليه علامات استفهام كثيرة).
- صدور الأوامر كان يأتي من جانب أي مسؤول: رئيس الأركان – وزير الحربية – القائد العام.. إلخ.
- انعدام التنسيق بين القوات.
- المخابرات الحربية أكدت أن طائرات إسرائيل لا تستطيع الطيران لأبعد من قناة السويس رغم أن مواصفات طائراتها كانت منشورة في المجلات العسكرية.
- غياب القيادات الميدانية.
- تم إغلاق مركز العمليات العام يوم 5 يونيو.
- قطع الإسرائيليون خط الاتصالات الرئيسي في سيناء أمام الجنود المصريين المسلحين دون أن يتدخلوا (تفسيري: عدم وجود أوامر بالتدخل وعدم وجود لامركزية).
- معدات تحمل ذخيرة لا تناسبها، ومعدات معطوبة (كان الجنود يدفعون بعض المركبات المعطوبة إلى الجبهة!).
- تم حشد آلاف الجنود بالجلاليب والبيجامات ودون توفير التموين اللازم أو أدوات لحفر حمامات في الصحراء.
- مع بدء الانسحاب هرب الضباط وتركوا الجنود.
- هروب الجيش تم دون حرق الوثائق أو تدمير الأسلحة والذخائر.
- هرب قائد الجيوش صلاح محسن من سيناء مع طاقم قيادته.
- رفضت مصر وقف إطلاق النار مساء 5 يونيو
- تم وضع خطة جيدة للانسحاب من شرق سيناء، ثم صدرت أوامر فورية بالانسحاب دون الخطة.
- تم تدمير معابر القناة بعد انسحاب الضباط وقبل عبور الجنود.
- الأشخاص المسؤولون عن الهزيمة تحديدا هم: جمال عبد الناصر – عبد الحكيم عامر – محمد فوزي رئيس الأركان  – اللواء صلاح محسن قائد الجيش.
