* Egypt public sector deterioration
  :PROPERTIES:
  :CUSTOM_ID: copy-of-egypt-public-sector-deterioration
  :END:
في مصر منشآت كثيرة جدا تابعة للدولة. تسمى منشآت القطاع العام. جميل جدا.
لكن هذه المنشآت حولها العاملون فيها الى خرابات.. أي أسقطوها وقضوا عليها
تماما لأن أمواله هي "فلوس الحكومة يابيه" يعني لا يهم أن يتم هدرها
والاستيلاء عليها. ومنذ فيلم العصفور ليوسف شاهين الذي صور بقلم ورؤية
اليساري المعروف، بتاع رأسمالية الدولة والقطاع العام والاشتراكية
الناصرية.. وخلافه، الأخ لطفي الخولي كاتب الفيلم، ونحن نعرف أن سرقة
القطاع العام حال وشغالة على ودنه... ولذلك أصبحت معظم منشآت القطاع العام
بما فيها التليفونات والكهرباء ودور الصحف والطيران والمؤسسات الثقافية مثل
هيئة قصور الثقافة وغيرها.. الخ شغالة فقط لكي يقبض العاملون رواتبهم
ولتوزيع المكافآت على جيوش الموظفين، لا من أجل تقديم خدمة للمواطنين..
والحكومة في ورطة حقيقية، فهي لا تستطيع ادارة هذه المؤسسات. لكنها لا
تستطيع أيضا إغلاقها لأنها لا تعرف كيف يمكنها التخلص من حيوش العاملين
والموظفين الذين جاء معظمهم اما بالوراثة أو بالواسطة أو بالتعيين القديم
عن طريق مكتب القوى العاملة من الأزمنة الغابرة... وبالتالي فالأزمة قائمة
ومستمرة. المؤسسات عاجزة عن أداء دورها.. والموظفون لا يعرفون ماذا يفعلون
فلا توجد لديهم خطة ولا برامج تدريب وتطوير ولا امكانية أيضا للتحديث...
والدولة عاجزة عن ايجاد البديل الحديث.. وجيوش الموظفين تطالب بـ "الطعام
لكل فم". لذلك أصبحت الدولة معطلة... صحيح هناك طرق وكباري والذي منه.. لكن
الادارة المدنية لجميع المؤسسات في حاجة- لا الى ثورة، بل الى "مكنسة"
ضخمة!
