* Facebook Power
  :PROPERTIES:
  :CUSTOM_ID: copy-of-facebook-power
  :END:
توقف فيسبوك لم يترتب عليه خسارة 7 مليارات للشركة؛ الحقيقة إن زوكربرج
بهذه الخسارة محظوظ أو متأمر، وخلينا نشوف الاحتمالين والنتيجة.

جايز تراجع شعبية المحتوى المقروء في العالم العربي مش موصل لكتير مننا
فكرة الزلزال الأكبر في تاريخ فيسبوك، واللي يفوق بمراحل فضيحة كامبريدج
أناليتكا اللي كان ليها الفضل الأول في موجة صعود اليمين المتطرف في الغرب.

منذ أيام، بدأت صحيفة «وول ستريت جورنال» بنشر سلسلة وثائق مسربة من أعلى
مستوى إداري وعملياتي في الشركة، والمعلومات مذهلة فعلا، ابتداءً من
الاستثناءات لكبار المؤثرين إلى ملاحقة مؤثرين آخرين ومعاقبتهم والتضييق
على أنشطتهم بالمنصة، مرورًا بقمع المحتوى الفلسطيني في مقابل التعامي عن
أنشطة متطرفة لصالح المكاسب التجارية، وصولاً إلى الخلاصة البحثية الداخلية
الأهم والأخطر في تقديري التي خلص إليها مهندسو البيانات في فيسبوك منذ 3
سنوات عن خطورة منصة إنستجرام على المراهقين.

قبيل توقف خدمات فيسبوك بساعات، كشف مصدر التسريب عن نفسه في واحد من أهم
البرامج التفلزيونية الأمريكية، وهي مهندسة بيانات في فيسبوك، يجري
الاستماع لشهادتها اليوم أمام الكونجرس، ضمن سلسلة إجراءات قانونية ممتدة
في التحقيق في الأضرار الاجتماعية والسياسية لفيسبوك.

توقف الخدمات سواء بسبب إعدادات في ال DNS أو غيره هو في الأخير إجراء لأحد
الموظفين، قد يكون أفضل مصادفة في تاريخ الشركة، أو المؤامرة الأكثر
إحكامًا لتأديب "العالم" حرفيًا بإظهار التأثير الإدماني وردة الفعل
الشعبية، واستوقفني هنا تعليق زوكربرج عند عودة الخدمات بإبراز "أهمية
خدمات فيسبوك في توصيل البشر بمن يهتمون بهم".

ما يجعل هذا الاحتمال قائمًا على الأقل هو أنها ليست المرة الأولى التي
يستل فيها زوكربرج سيف شركته ويستعرض حدته وبطشه في وجوه حكومات العالم،
ففي فبراير 2021 وعلى إثر قانون أسترالي معقد (وغبي) ضد الشركات التقنية،
تجاوب جوجل وحاول التماهي مع الإجراءات، لكن فيسبوك أوقف جميع خدماته في
أستراليا لأيام ومنع غير الاسترالين من الاطلاع على أي خبر من داخل
أستراليا، ما استدعى خروج الحكومة ببيانات وخطابات بلهجة عاطفية
واستجدائية، ولم يمر القانون كما أرادت أستراليا.

في الأخير ومجددًا، أتمنى أن تلقى تسريبات فيسبوك الاهتمام الكافي عربيًا،
وبالأخص فيما يتعلق بأسلوب الحياة الضار في إنستجرام وغيره من المنتجات
الأخطر التي تشبه تيكتوك وبدأ فيسبوك في ترويجها داخل فيسبوك نفسه؛ غني عن
التفصيل حاليًا الضرر الاجتماعي على المدى البعيد لمنصة تيكتوك التي تعد من
أكبر استثمارات الصين التقنية إن لم تكن أكبرها على الإطلاق وأكبر أدواتها
في حروبها النفسية.
