#+TITLE: Nsg


/nsg/ - Natsoc General ϟϟ Your one-stop-shop for every redpill known to /pol/ ϟϟ

Thread for discussion of the Jewish Question, Race Realism, Anti-Communism, the Aryan Ideal,
Traditionalism, Racial Nationalism, and Racial Identity Movements.

Improve yourself, comrades, community, and folk.  > 卐 - SMASH (((MARXISM)))!  > 卐 - PURGE
DEGENERACY!  > 卐 - DISMANTLE ZOG!

卐 - SECURITY FIRST - Follow this guide to stop your ISP from spying on your browser
traffic, and to view blocked sites.  https://imgur.com/ijqKqtm

卐 - IF YOU DO NOT SEE A GENERAL IN THE CATALOG COPY FROM THE PASTEBIN & START ONE /NSG/ -
http://pastebin.com/vPZPyDhK

ᛉ - ARE YOU NEW TO /NSG/ START HERE >The Optics of Ineffectiveness
https://thepurityspiral.com/?p=630 >The Many Faces of National Socialism by Karl Radl
https://thepurityspiral.com/?p=638卐 - NATSOC Philosophy and Economics
https://pastebin.com/zR1vQcK1 ᛉ - Right-wing E-Books and Film archives
https://pastebin.com/MA25jmUP卐 - NEWS, RADIO, COMMENTARY & FORUMS
https://pastebin.com/NqJepJVV ᛉ - ARYANISM and RACIAL ANTHROPOLOGY
https://pastebin.com/5u2aWMcw卐 - SOURCES on JEWS and COMMUNISM
https://pastebin.com/eEuQBFBH ᛉ - GAYS, TRANS, LGBT - THE DEGENERACY AGENDA
https://pastebin.com/yJqc9KJC卐 - EXPOSING THE CULTURAL MARXIST AGENDA
https://pastebin.com/Y3Df8ejJ ᛉ - WHITE GENOCIDE & JEWISH INFLUENCE
https://pastebin.com/5fBEEAzc卐 - Jews and the Porn Industry https://pastebin.com/9SKE1fmQ
ᛉ - HISTORY - WHAT CAUSED THE WAR, WHAT FOLLOWED AFTER?  https://pastebin.com/idiLNzzT卐 -
MYTHS ABOUT GENERALPLAN OST AND LEBENSRAUM https://pastebin.com/DjMLkBa5 ᛉ - Religion,
Spirituality, and Esotericism In the 3rd Reich https://pastebin.com/1iYJ89yN卐 - HOLOHOAX
Resources https://pastebin.com/HKYnk3Mb ᛉ - ANTHEMS/TRIBUTES https://pastebin.com/XwJwWSLc
卐 - RACE MIXING AND WHY IT'S BAD http://pastebin.com/tGMEhbhf ᛉ - Misc Topics
https://pastebin.com/cD25gxLv

============================ CONTENTS
--------

>ARCHIVED ROPECULTURE ARTICLES: https://pastebin.com/rCykseWx >/POL/ EBOOKS ARCHIVE
http://mega.nz/#F!B4dB2SzQ!h_pMC30v2a_y31iD0dy0sg >Self-improvement archives
https://mega.nz/#F!ZuZmiBqZ!XhyEetUaj6an8ntb-U1AZw >Ironmarch Publications Archive
https://mega.nz/#F!ZaAgDbzT!aGwQn3grHN-Qea8e0Zyq-Q!wDRS2CQJ >3rd Reich publications Archive
https://mega.nz/#F!5Q5UFZIR!MvGFhWEPb03Qg3ZFOh5yKg

ᛉ - IF YOU DO NOT SEE A GENERAL IN THE CATALOG COPY FROM THE PASTEBIN & START ONE /NSG/ -
http://pastebin.com/vPZPyDhK

ᛉ - NEWS, RADIO, COMMENTARY & FORUMS http://autonom.pl/ https://judas.watch/
https://thepurityspiral.com/ https://fashcast.org/articles/ http://www.xryshaygh.com/en
http://coincidencedetector.com/ https://ordoevangelistarum.com/
http://democratieparticipative.biz/ https://www.nordfront.se/our-path-2

卐 - THE SCIENCE OF RACE >Diversity + Proximity = War:
https://mega.nz/#F!UvpEHJ4b!sn00aYPdrx_yS-W70fAcIw >Race and Sex Differences in Intelligence
by Helmuth Nyborg http://libgen [dot] io/book/index.php?md5=1792DBBF0D866D2476E1455DD8DAFF0F
>Human Accomplishment - Charles Murray
https://www.gwern.net/docs/2003-murray-human-accomplishment.pdf >Dysgenics: Genetic
Deterioration in Modern Populations http://docdro.id/avPyEsh >Race Differences in
Intelligence by Richard Lynn http://docdro.id/e2pEr1E https://pastebin.com/Q1hMEC4a
http://humanbiologicaldiversity.com/


卐 - ARYANISM ============= ">We document a southward spread of genetic ancestry from the
Eurasian Steppe, correlating with the archaeologically known expansion of pastoralist sites
from the Steppe to Turan in the Middle Bronze Age (2300-1500 BCE)."
https://www.thequint.com/voices/opinion/genomic-study-vedic-aryan-migration-dravidian-languages-sanskrit
>In India, members of higher ranking castes are genetically more similar to Europeans, while
lower castes are more similar to Asians.
http://www.sciencedaily.com/releases/2001/05/010515080044.htm
http://www.sciencedaily.com/releases/2009/09/090923143333.htm Some quotes from the Rigveda,
the oldest Indo-European text.  >"At the swift draught the Soma-drinker waxed in might, the
Iron One with yellow beard and yellow hair. He, Lord of Tawny Coursers, Lord of fleet-foot
Mares, will bear his Bay Steeds safely over all distress." Indra - 10.96.8 >"Indra throws
drops of moisture on his yellow beard." Indra - 10.23.4 >"The swarthy skin, the hated of
Indra" - Rigveda IX 73.5 >The Rig Veda praises the God who "destroyed the Dasyans and
protected the Aryan colour." - Rigveda. III 34.9 >"Indra protected in battle the Aryan
worshipper, he subdued the lawless for Manu, he conquered the black skin." - Rigveda. I
130.8 >The Rigveda thanks God for "scattering the slave bands of black descent", and for
stamping out "the vile Dasyan colour." - Rigveda. II.20.7, II 12.4 >This choice sums up the
Aryans opinion of their non-white subjects: "Black skin is impious" - Rigveda. II.12.4
http://www.thehindu.com/sci-tech/science/how-genetics-is-settling-the-aryan-migration-debate/article19090301.ece
>A study by Hellenthal et al. (2014) on the DNA of the Kalash people showed evidence of
input from modern day Germany and Austria between 990 and 210 BC, a period that overlaps
with that of Alexander the Great...
http://www.well.ox.ac.uk/~gav/admixture/2014-science-final/resources/FAQ.pdf
http://www.cell.com/ajhg/fulltext/S0002-9297(15)00137-8


卐 - NATSOC ECONOMICS ===================== >NatSoc German Economic Policy
http://mk.christogenea.org/podcasts/national-socialist-german-economic-policy-part-1-june-15th-2013
http://www.nber.org/chapters/c9480.pdf
http://www.historylearningsite.co.uk/nazi-germany/nazi-germany-military-expenditure/
https://www.cambridge.org/core/journals/journal-of-economic-history/article/div-classtitlethe-role-of-private-property-in-the-nazi-economy-the-case-of-industrydiv/5853885D956348A13B5CEFDC42313E2B
http://www.academia.edu/1527919/Different_Ends_Similar_Means._The_International_Trade_and_Payments_Regimes_of_Nazi_Germany_and_Soviet_Union_with_Eastern_Europe_1939-1956
>Against the Mainstream: Nazi privatization in 1930's Germany (Germa Bel)
http://www.ub.edu/graap/EHR.pdf >The Coining of “Privatization” and Germany’s National
Socialist Party (Germa Bel) https://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.20.3.187
http://voxeu.org/article/macroeconomics-germany-forgotten-lesson-hjalmar-schacht
https://youtu.be/pKnFN8P21-0 >William Joyce – Twilight Over England
http://archive.org/details/WilliamJoyceTwilightOverEngland >Jewish Domination Of Weimar
Germany 1919-1932, Eckart-Verlag
http://archive.org/details/JewishDominationOfWeimarGermany1919-1932 >Arthur Pillans Laurie -
The Case for Germany: A Study of Modern Germany http://archive.org/details/TheCaseForGermany
>Adolf Ehrt - Communism in Germany http://archive.org/details/CommunismInGermany >Gottfried
Feder - The Program Of The NSDAP
http://archive.org/details/GottfriedFeder_TheProgramOfTheNSDAP >Gottfried Feder - Manifesto
For The Abolition Of Interest Slavery
http://archive.org/details/GottfriedFederManifestoForTheAbolitionOfInterestSlavery1919
>Social Welfare in Germany: https://archive.org/details/SocialWelfareInGermany >German
Economic Policy: https://archive.org/details/GermanEconomicPolcy >German Labour Service:
https://archive.org/details/FermanLabourServise >Paul Einzig - Economic Foundations Of
Fascism https://archive.org/details/EconomicFoundationsOfFascismP.Einzig


SOURCES on JEWS and COMMUNISM - Part I ======================================
https://semiticcontroversies.blogspot.com/2010/04/sources-on-jews-and-communism-part-i.html
https://semiticcontroversies.blogspot.com/2010/04/sources-on-jews-and-communism-part-ii.html
http://semiticcontroversies.blogspot.com/2010/04/sources-on-jews-and-communism-part-iii.html
http://semiticcontroversies.blogspot.com/2010/04/sources-on-jews-and-communism-part-iv.html
http://semiticcontroversies.blogspot.com/2010/04/sources-on-jews-and-communism-part-v.html
https://semiticcontroversies.blogspot.com/2010/05/sources-on-jews-and-communism-part-vi.html
https://semiticcontroversies.blogspot.com/2010/05/sources-on-jews-and-communism-part-vii.html
https://semiticcontroversies.blogspot.com/2010/05/sources-on-jews-and-communism-part-viii.html
https://semiticcontroversies.blogspot.com/2010/05/sources-on-jews-and-communism-part-ix.html
https://semiticcontroversies.blogspot.com/2010/06/sources-on-jews-and-communism-part-x.html
https://semiticcontroversies.blogspot.com/2010/06/sources-on-jews-and-communism-part-xi.html
https://semiticcontroversies.blogspot.com/2010/07/sources-on-jews-and-communism-part-xii.html
>Father Georgiy Gapon and the Jewish Origins of Russia’s Bloody Sunday:
http://www.semiticcontroversies.blogspot.com/2015/03/father-georgiy-gapon-and-jewish-origins.html
>How the Jews were responsible for the Murder of Tsar Nicholas II:
http://www.semiticcontroversies.blogspot.com/2013/08/jews-bolsheviks-and-murder-of-tsar.html
>Comintern 1919-1943:
http://www.semiticcontroversies.blogspot.com/2010/05/sources-on-jews-and-communism-appendix.html
>The Gulag Archipelago:
http://www.semiticcontroversies.blogspot.com/2011/12/jews-of-gulag-archipelago.html
>Nationalities of NKVD Officials involved in the Purges:
http://www.semiticcontroversies.blogspot.com/2013/09/nationalities-of-nkvd-purge-officials.html


SOURCES on JEWS & COMMUNISM - Part II ============ >Debunking the whole ‘Stalin was a jew’
thing: http://www.semiticcontroversies.blogspot.com/2012/05/was-stalin-jewish.html >The
Marxist philosopher Louis Althusser and the jewess who drove him literally insane:
http://www.semiticcontroversies.blogspot.com/2013/01/louis-althussers-jewish-problem.html
>The Jews behind the Hungarian Soviet Republic of 1919:
http://www.semiticcontroversies.blogspot.com/2016/03/the-jewish-role-in-hungarian-soviet.html
>Lithuania (1919-1941):
http://www.semiticcontroversies.blogspot.com/2016/02/jews-and-communism-in-lithuania-1918-to.html
>Moldova/Moldavia (1921-1941):
http://www.semiticcontroversies.blogspot.com/2013/09/jews-and-communism-in-moldovamoldavia.html
>Moldova/Moldavia (1941-1991)
https://semiticcontroversies.blogspot.com/2013/10/jews-and-communism-in-moldova-june-1941.html
Hungary (post-1919):
http://www.semiticcontroversies.blogspot.com/2012/06/in-brief-recent-article-on-jews-and.html
>Louis Budenz’s testimony:
http://www.semiticcontroversies.blogspot.com/2011/12/jews-and-communism-according-to-louis.html
>Whittaker Chambers’ testimony:
http://www.semiticcontroversies.blogspot.com/2011/01/jewish-communist-espionage-in-united.html
>Richard Krebs’ testimony:
http://www.semiticcontroversies.blogspot.com/2011/12/richard-krebs-soviet-intelligence-and.html
>South Africa:
http://www.semiticcontroversies.blogspot.com/2010/06/twelve-prominent-jewish-anti-apartheid.html
>How jews created Modern Afrocentrism:
https://semiticcontroversies.blogspot.com/2014/05/martin-bernal-and-melville-herskowitz.html
>Fidel Castro was jewish:
http://www.semiticcontroversies.blogspot.com/2017/02/was-fidel-castro-jewish.html >Jews
behind the Cuban Communist Revolution:
http://www.semiticcontroversies.blogspot.com/2017/02/the-jews-behind-fidel-castro-and-cuban.html
>Che Guevara’s jewish girlfriend:
http://www.semiticcontroversies.blogspot.com/2012/03/haydee-tamara-bunke-bider-jewish.html


SOURCES on JEWS & COMMUNISM - Part III ============ >The Jewish-Bolshevik Decimation of the
Russian People https://youtu.be/-C1BFs5HQLc >Jewish financiers and the Russian Revolution
http://youtu.be/Qa-dInQEa-4 >Putin confirms, 85% Jews behind Bolshevism
http://youtu.be/j6p1zxKnDeM http://volokh.com/2011/10/29/communism-and-the-jews/ Communism
was Jewish - Communism is Jewish http://www.controversyofzion.info/communism_was_jewish.htm
Communism's Death Toll, and the Jewish Role in Bolshevism
https://youtube.com/watch?v=km6u4L1JsmY A Jew in Mao's China
http://blogs.forward.com/the-arty-semite/159051/a-jew-in-maos-china/ Jews and Marxism -
Socialism - Communism http://www.come-and-hear.com/dilling/chapt11.html The Jewish Bolshevik
Commies http://trutube.tv/video/1013/The-Jewish-Bolshevik-Commies >The Jewish Century by
Yuri Slezkine
https://www.docdroid.net/kXW5Tab/yuri-slezkine-the-jewish-centurybookzzorg.pdf.html Jewish
Communists http://www.jewwatch.com/jew-communists.html Jewish Founders of International
Communism http://www.jewwatch.com/jew-communists.html Jewish Pre-Eminence in the Political
Left/Communism http://www.holywar.org/jewishtr/commun.htm The Jewish Role in the Bolshevik
Revolution and Russia's Early Soviet Regime http://www.ihr.org/jhr/v14/v14n1p-4_Weber.html
Jewish Activists Created Communism
http://www.truthtellers.org/alerts/jewishactivistscommunism.html Jewish Bolsheviks
http://www.liveleak.com/view?i=cf7_1256305898 Jewish Bolshevism
https://en.wikipedia.org/wiki/Jewish_Bolshevism Jewish Faces in Chinese Government
http://jewishfaces.com/china.html


卐 - GAYS, TRANS, LGBT - THE DEGENERACY AGENDA
============================================== Required viewing:
https://youtu.be/BPgq1c4TYi4 https://youtu.be/oN4w8e432_o https://youtu.be/56Bc9UoxklQ
Homesxuality EXPLICITLY linked to Pedophilia: https://pastebin.com/ETuhB7wJ
https://youtu.be/gXGlawiibK8 >Marcuse on Revolutionary Homosexuality
https://oldhickorysweblog.blogspot.com/2011/02/frankfurt-school-1938-herbert-marcuse.html
http://libgen.io/book/index.php?md5=481C95B3EF929689CD28294ADED66CD4 >Homosexuality and The
Politics of Diagnosis (pp. 105-112)
http://libgen.io/book/index.php?md5=8DA04054E0325E06202DBE12719AF420


卐 - EXPOSING THE CULTURAL MARXIST AGENDA ========================================= >The
Frankfurt School of Social Research and the Pathologization of Gentile Group Allegiances
http://www.kevinmacdonald.net/chap5.pdf >Jonathan Bowden on Cultural Marxism:
https://youtu.be/aR4MvD9IEAE https://youtu.be/Yaf1192EZfI https://youtu.be/J92f2S3E0S8
>Cultural Marxism: The Corruption of America https://www.youtube.com/watch?v=gIdBuK7_g3M
>Erich Fromm, Judaism and the Frankfurt School
http://pages.gseis.ucla.edu/faculty/kellner/Illumina%20Folder/kell24.htm >Frankfurt School
of Social Research http://jettandjahn.com/2010/10/frankfurt-school-of-social-research/ >The
Frankfurt School & Cultural Marxism https://www.youtube.com/watch?v=ghx3d1GiAc0
https://www.youtube.com/watch?v=fkcy7256tBM https://www.youtube.com/watch?v=fG6TcYfpQOg >The
History of Political Correctness https://www.youtube.com/watch?v=acjIw7cVc2k >How a Handfull
of Marxist Jews Turned Western and U.S. Culture Upside Down
http://davidduke.com/how-a-handfull-of-marxist-jews-turned-western-and-us-culture-upside-down/
>The Jewish Frankfurt School and the End of Western Civilization
http://www.dailystormer.com/the-jewish-frankfurt-school-and-the-end-of-western-civilization/
>The New Dark Age: The Frankfurt School and "Political Correctness"
http://www.schillerinstitute.org/fid_91-96/921_frankfurt.html >Who Stole Our Culture?
http://www.wnd.com/2007/05/41737/ >The Frankfurt School and Its Legacy
http://www.morveninstituteoffreedom.com/FrankfurtSchool.pdf >Critical Theory (Cultural
Marxism) and Jewish Thought
http://www.nottingham.ac.uk/theology/events/2013/critical-theory-and-jewish-thought.aspx
>Fallen Jews, Critical Theory, and Cultural Marxism
https://originsofleftism.wordpress.com/2015/01/16/notes-fallen-jews-critical-theory-and-cultural-marxism/


卐 - WHITE GENOCIDE & JEWISH INFLUENCE ====================================== >RABBI Yosef
Tzvi Ben Porat explains why Hitler hated Jews.  https://youtu.be/33zAu3IDW6w >Rabbi admits
that Muslims are Jews work together against Europe https://youtu.be/wb_4U2UJucE >E. Michael
Jones - Poland: Jewish "Paradise" https://youtu.be/Xt-siQyLQ9E >Endgame - White Genocide
http://youtu.be/uMfk5UeGw4E >THE JEWISH QUESTION https://youtu.be/v1jtKNs5q2o >The Talmudic
basis of Jewish supremacy http://youtu.be/CEAmtWd6aD0 >Miscegenation illegal in (((Our
Greatest Ally))) http://youtu.be/5NdQXOPARWI >Jews pushing immigration for white nations
http://youtu.be/XpnYpQaHAuc >Barbara Lerner Spectre http://youtu.be/oZ1BRHBErH8 >Jewish
Supremacism https://youtu.be/asKUoISLeo4 >Noel Ignatiev https://youtu.be/q90kmUbEv7c
>Mainstreaming white genocide http://youtu.be/RC-Cqkq6zWc >Sarkozy on forced misecegenation
http://youtu.be/I8yaiN6ew_g >Ben Freedman on World Zionist wars http://youtu.be/x8OmxI2AYV8
>Alon Ziv promoting interracial couples http://youtu.be/8RWP8Pws9mw >Alon Ziv defending Jews
refusing to breed outside their race http://archive.is/1Mzb9 >The Frankfurt School of
Cultural Marxism http://youtu.be/QY82qNWMaaE


卐 - Jews in High Places >Judaism's Strange Gods
http://libgen.io/book/index.php?md5=14CC18CA94E9910E9B703DAF5807C63E >Judaism Discovered: A
Study of the Anti-Biblical Religion of Racism, Self-Worship, Superstition and Deceit
http://libgen.io/book/index.php?md5=CE6794C7D93FAEAB5ABEC8EA9238B138 >Blood Passover - Rabbi
Ariel Toaff http://www.israelshamir.net/BLOODPASSOVER.pdf >The Soul of a Jew and the Soul of
a Non-Jew http://www.hakirah.org/Vol%2016%20Balk.pdf >Rome and Jerusalem by Moses Hess
https://archive.org/details/romeandjerusale02waxmgoog >200 Years together by Aleksandr
Solzhenitsyn https://my.mixtape.moe/adkmzj.pdf >Germany Must Perish by Kaufman
https://wikispooks.com/wiki/File:Germany_Must_Perish.pdf >The Jewish Century by Yuri
Slezkine https://www.docdroid.net/kXW5Tab/yuri-slezkine-the-jewish-centurybookzzorg.pdf.html
>You Gentiles by Maurice Samuels https://archive.org/details/YouGentiles_414 >Steinlight:
'The Jewish Stake in America's Changing Democracy'
http://cis.org/articles/2001/back1301.html https://archive.is/2najE
https://thezog.wordpress.com/who-controls-hollywood/
https://thezog.wordpress.com/who-controls-big-media/
https://thezog.wordpress.com/who-controls-the-senate/
https://thezog.wordpress.com/who-controls-the-economy/
https://thezog.wordpress.com/who-controls-the-congress/
https://thezog.wordpress.com/who-controls-goldman-sachs/
https://thezog.wordpress.com/who-controls-the-ivy-league/
https://thezog.wordpress.com/who-controls-the-news-part-1/
https://thezog.wordpress.com/who-controls-the-think-tanks/
https://thezog.wordpress.com/who-controls-the-supreme-court/
https://thezog.wordpress.com/who-controls-wall-street-part-1/
https://thezog.wordpress.com/who-controls-the-state-department/
https://thezog.wordpress.com/who-controls-the-treasury-department/
https://thezog.wordpress.com/who-controls-american-international-group/
https://thezog.wordpress.com/who-controls-the-federal-reserve-system-part-1/



卐 - Jews and the Porn Industry
----------------------------
> Nathan Abrams on Jews in the Porn Industry https://archive.fo/5x0oK > The Jewish Masters
of Porn https://archive.fo/UcEfk > Pornography, sex slaves, prostitution… Why are these
businesses dominated by Jews?
http://hugequestions.com/Eric/TFC/the_pornography_business.html > Jewish Porn Star James
Deen–“The Jews know we’re better than everyone else. That’s all that matters. It’s true.
We’re the Chosen People. It’s a fact.”  https://archive.fo/joKnY > Interracial Porn Isn't
Profitable http://archive.is/5Xev4 >Jewish Professor of American History at Aberdeen
University in UK, Prof. Nathan Abrams. He boasts that Jews were the driving force of the
modern pornographic industry and that their motivation is in part to destroy Gentile morals.
https://archive.fo/bO7us

卐 卐 卐 卐 卐 卐

Anti-Porn Thread >https://archive.is/bVdt6

> Neural Correlates of Sexual Cue Reactivity in Individuals with and without Compulsive
 Sexual Behaviours http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0102419
 > Brain Structure and Functional Connectivity Associated With Pornography Consumption
 http://archpsyc.jamanetwork.com/article.aspx?articleid=1874574 > Brown University:
 Pornography
 http://brown.edu/Student_Services/Health_Services/Health_Education/sexual_health/sexuality/pornography.php
 > The Social Costs of Pornography
 http://www.internetsafety101.org/upload/file/Social%20Costs%20of%20Pornography%20Report.pdf
 > The Effects of Pornography on Individuals,Marriage, Family and Community
 http://www.scribd.com/doc/23930556/The-Effects-of-Pornography-on-Individuals-Marriage-Family-and-Community
 > Porn, Novelty and the Coolidge Effect
 http://yourbrainonporn.com/porn-novelty-and-the-coolidge-effect > Porn Stars without
 Make-up: Death of the Illusion
 http://www.buzzfeed.com/ryanhatesthis/33-startling-photos-of-pornstars-with-and-without-their-make#.dsYORdANA
 > Physiological and Psychologica Effects of Modern Day Pornography
 http://yourbrainonporn.com/physiological-and-psychological-effects-modern-day-pornography-2013
 > Philip Zimbardo TED Talk: The Demise of Guys http://www.ted.com/talks/zimchallenge > Gary
 Wilson: The Great Porn Experiment https://www.youtube.com/watch?v=vTD_itXrR6E > Adolescent
 Brain Meets Highspeed Internet Porn
 https://www.youtube.com/watch?v=XvyejdlmKpE&feature=youtu.be > Viewers of Pornography Have
 a Smaller Reward System
 https://www.mpib-berlin.mpg.de/en/media/2014/06/viewers-of-pornography-have-a-smaller-reward-system
 > Adult Film Performers Transmission and STI Prevelace
 http://www.aidshealth.org/wp-content/uploads/2013/06/Adult-film-poster-STD-Prevention-2014.pdf
 > The Documented Effects of Pornography
 http://forerunner.com/forerunner/X0388_Effects_of_Pornograp.html > Fight the New Drug: Porn
 Harms in Three Ways http://fightthenewdrug.org/get-the-facts/ > Harm of Pornography
 http://www.internetsafety101.org/harmsofpornography.htm > 9 Things You Should Know About
 Pornography and The Brain
 http://www.thegospelcoalition.org/article/9-things-you-should-know-about-pornography-and-the-brain



卐 - HISTORY - WHAT CAUSED THE WAR, WHAT FOLLOWED AFTER? (1)
-------------------------------------------------------
>Individual Jewish intellectuals such as Bernard Baruch, Lehman, Governor of New York State,
Felix Frankfurter, the newly appointed Supreme Court Judge, Morgenthau, the Financial
Secretary, and other well-known personal friends of Roosevelt have taken a prominent part in
this campaign of hatred. All of them want the President to become the protagonist of human
liberty, religious freedom and the right of free speech . . .

>This particular group of people, who are all in highly placed American official positions
and who are desirous of being representatives of 'true Americanism', and as 'Champions of
Democracy', are, in point of fact, linked with international Jewry by ties incapable of
being torn asunder.

>For international Jewry -- so intimately concerned with the interests of its own race --
President Roosevelt's 'ideal' role as a champion of human rights was indeed a godsend. In
this way Jewry was able not only to establish a dangerous centre in the New World for the
dissemination of hatred and enmity, but it also succeeded in dividing the world into two
warlike camps. The whole problem is being tackled in a most mysterious manner. Roosevelt has
been given the power to enable him to enliven American foreign policy and at the same time
to create huge reserves in armaments for a future war which the Jews are deliberately
heading for.

Source: -- Polish Ambassador at Washington, Count Jerzy Potocki, in a report to the Polish
Foreign Office, dated January 12, 1939; Quoted in J. F. C. Fuller, A Military History of the
Western World, vol. 3, pp. 372-374 http://www.fpp.co.uk/History/General/Potocki/papers.html


卐 - HISTORY - WHAT CAUSED THE WAR, WHAT FOLLOWED AFTER? (2)
-------------------------------------------------------

>"Herr Foerster cited the opinions of Britons and Frenchmen including Mr Lloyd George and Mr
 Churchill to the effect that 'the Polish corridor was a mistake', hissed when he read out
 inflammatory statements by Polish newspapers, including the statement in 'Czas' that Poland
 would blow Danzig to bits if it united with Germany and the recent threat by Marshal
 Smigly-Rydz that Danzig would be the first stage in a cruisade against Germany."
- The Advertiser, 12 August 1939
http://trove.nla.gov.au/newspaper/article/41083410?searchTerm=Smig%26%23322%3By-Rydz

>"General Sosnkowski, second-in-command of the Polish army, declared : — 'Pilsudski's
 legionnaires were particularly favoured by history because it seems that they will
 partcipate in a second international war in which Poland will be one of the most important
 and most exposed actors in the drama'."
- Kalgoorlie Miner, 7 August, 1939
http://trove.nla.gov.au/newspaper/article/94852275?searchTerm=sosnkowski

http://trove.nla.gov.au/ndp/del/article/46414370?searchTerm=sosnkowski&searchLimits=exactPhrase|||anyWords|||notWords|||l-textSearchScope=*ignore*%7C*ignore*|||fromdd=01|||frommm=08|||fromyyyy=1939|||todd=31|||tomm=08|||toyyyy=1939|||l-word=*ignore*%7C*ignore*|||sortby

http://trove.nla.gov.au/ndp/del/article/68316591?searchTerm=sosnkowski&searchLimits=exactPhrase|||anyWords|||notWords|||l-textSearchScope=*ignore*%7C*ignore*|||fromdd=01|||frommm=08|||fromyyyy=1939|||todd=31|||tomm=08|||toyyyy=1939|||l-word=*ignore*%7C*ignore*|||sortby

http://trove.nla.gov.au/ndp/del/article/98597109?searchTerm=sosnkowski&searchLimits=exactPhrase|||anyWords|||notWords|||l-textSearchScope=*ignore*%7C*ignore*|||fromdd=01|||frommm=08|||fromyyyy=1939|||todd=31|||tomm=08|||toyyyy=1939|||l-word=*ignore*%7C*ignore*|||sortby


卐 - HISTORY - WHAT CAUSED THE WAR, WHAT FOLLOWED AFTER? (2)
-------------------------------------------------------
>What the world rejected: Hitler's offers of peace
https://www.wintersonnenwende.com/scriptorium/english/archives/nothanks/wwr00.html >Viktor
Suvarov - Who started the 2nd World War?  https://youtu.be/SbBnRZoTHFs >Hitler's War - the
Allies caused the war http://youtu.be/MejbBsSAP8I >Stalin's plans to invade Europe, proving
Hitler's invasion of Russia was preemptive:
https://www.wintersonnenwende.com/scriptorium/english/archives/articles/stalwarplans.html
>See also: "The Chief Culprit" by Victor Suvarov in the ebooks archive:
https://mega.nz/#F!B4dB2SzQ!h_pMC30v2a_y31iD0dy0sg!o0Uk3KTJ >Polish massacres of ethnic
Germans (Note - most bodies discovered as Germans invaded were in an advanced state of
decay, thus, the common excuse "they were killed BECAUSE Germany invaded" can't explain why
they were dead for so long; many killings involved elaborate desecration, dismemberment, and
mocking disfigurements of the bodies - things not done in haste)
https://www.wintersonnenwende.com/scriptorium/english/archives/deathinpoland/dp00.html
http://www.danzigfreestate.org/unknownhistory.htm https://archive.is/MitYS
https://archive.is/JauWN >The Jewish lobby, (((Stephen Wise))), (((Morgenthau))), and FDR
https://inconvenienthistory.com/5/2/3209 https://inconvenienthistory.com/6/2/3294 >The
Jewish lobby, (((Bernard Baruch))) and Churchill's 'The Focus'
http://www.fpp.co.uk/bookchapters/WSC/Waley_Cohen.html >Britain's promises to Poland
http://jane-griffiths-my-book.blogspot.com/2013_03_01_archive.html
http://www.worldfuturefund.org/wffmaster/Reading/History/polandbetrayal.htm >Why Germany
Invaded Poland http://youtu.be/pe0gIdVgeow http://youtu.be/oSLy5qn7q7c
http://youtu.be/DL_0xA5bVrE >Eisenhower's Rhine-Meadows Death Camps
https://youtu.be/hbp61fOVFaE >Hellstorm - Post-war Genocide of Germans
http://youtu.be/qkQ6J5F01Do http://youtu.be/LwAYgjG6SkM >The Rape of Berlin
http://youtube.com/watch?v=Xdr4-B0q19E&feature=youtu.be


卐 - MYTHS ABOUT GENERALPLAN OST AND LEBENSRAUM
===============================================

'Lebensraum' is often intentionally exaggerated by those wanting to push the fractal "Hitler
planned to exterminate all races" meme. The actual meaning of Lebensraum referred to the
security of the German borders, and the need to provide living space so that Germans aren't
threatened by outside forces. The primary focus of Lebensraum were the Volksdeutch (Germans
held is former German lands after the redrawn map of Versailles) populations and former
German lands used to create Poland and Czechoslovakia under the Treaty of Saint Germain. To
claim that "living space" meant "exterminate and re-populate more land than there would have
been Germans to inhabit" is absurd, and contradicts the policies of "Germanization" that
were ACTUALLY PRACTICED by Germans regarding occupied peoples:

https://www.youtube.com/watch?v=8ra-ChcOiuU

Hitler didn't consider Russians subhuman. He considered them inferior. Because in terms of
living, they were. Seriously, look at the living style of the average Soviet, then compare
them to a German in 1930, they were, by all accounts inferior. He even talks about how some
Russians of the old rich class were Germanic. There were multiple reasons for the invasion
of the Soviet Union, for example: >1. To gain the necessary resources to fuel a long time
war, something that Germany was severely lacking.  >2. To prevent the inevitable invasion of
Europe by the Soviet Union. If you gonna start a war, it's best to have the first strike.
>3. To disband the Bolshevik and Jewish regime in the Soviet Union, something Hitler knew
would be a threat to Germany.

True, the Germans would've gained land from defeating the Soviets and would certainly have
sent its citizens into this newfound land, just like the allies did to German clay they
gained after WW1 and WW2. The Germans wouldn't have exterminated Russians. They simply would
have governed them.

卐 - MYTHS ABOUT GENERALPLAN OST AND LEBENSRAUM
===============================================

In summary...

1. There is absolutely no proof of Generalplan Ost ever existing.
2. Hitler would have been fine with a path through the Polish Corridor. If Poland had agreed to the terms then there would have been no war.
3. Germany did not massively blob into Eastern Europe like wiki suggests, they had very clear borders. The eventual goal was to set up puppet states, not wipe out the populace.
4. If the plan was to exterminate Slavs, then why were there no camps for that purpose? The deaths in Eastern Europe are from starvation and warfare, not extermination.
5. Plenty of Slavs fought alongside Germans in the Russian Liberation Army, SS Galician, and others.
*6. "Dokument 1880' is a letter from Himmler to Hitler discussing Himmler's "Germaneizerung"
(Germanization) Plan for occupied peoples of the East. The objective was to forcibly
assimilate them in the shortest amount of time, mostly by importing foreign children to
Germany and "Germanizing" them with new German names, and German educations. This was also
the basis of the "Lebensborn Kidnapping Trials", so the assertion that Germany meant to
"exterminate" slavs contradicts the other myth, that Germany "kidnapped" slavic children to
"erase their identities". (See Page 147 of
www.loc.gov/rr/frd/Military_Law/pdf/NT_war-criminals_Vol-XIII.pdf )


卐 - HITLER'S USES OF THE WORD "LEBENSRAUM" in MEIN KAMPF
==================================================== The word appears nine times in Mein
Kampf.

"Einmal tritt aber dieser Fall ein, und zwar um so früher, je kleiner der zur Verfügung
stehende Lebensraum eines Volkes ist."  >But this case occurs once, and the smaller the
available living space of a people

"Er ist nicht eine Zusammenfassung wirtschaftlicher Kon-trahenten in einem bestimmt
umgrenzten Lebensraum zur Erfüllung wirtschaftlicher Aufgaben" >It is not a summary of
economic contenders in a defined (living) environment for the fulfillment of economic tasks

"um diese unter allerlei Vorwänden für sich schaffen zu lassen, können selbst ohne jeden
eige- nen, bestimmt begrenzten Lebensraum Staaten bilden. Dies trifft in erster Linie zu bei
dem Volke, unter dessen Para- sitentum besonders heute die ganze ehrliche Menschheit zu
leiden hat: dem Judentum."  >To all these pretexts for themselves, without any countries.
This applies primarily to the people, under who the whole of honest humanity today has
suffered: Judaism.

"Der Nomade besitzt sehr wohl einen bestimmt um-grenzten Lebensraum, nur bebaut er ihn nicht
als seßhafter Bauer, sondern lebt vom Ertrage seiner Herden, mit denen er in seinem Gebiete
wandert. Der äußere Grund hierfür ist in der geringen Fruchtbarkeit eines Bodens zu sehen,
der eine Ansiedlung einfach nicht gestattet. Die tiefere Ur-sache aber liegt im zwischen der
technischen Kultur einer Zeit oder eines Volkes und der natürlichen Armut eines
Lebensraumes."  >The nomad has a bordered habitat, he did not cultivate as a more settled
peasant, but lives by the yield of his flocks, with those he walks in his territory. The
external reason for this is to be seen in the low fertility of a soil, which does not allow
settlement. There is a disproportion between the technical culture of a time or a people and
the natural poverty of a living space.

"Bei den Juden hingegen ist diese Einstellung überhaupt nicht vorhanden; er war des-halb
auch nie Nomade, sondern immer nur Parasit im Körper anderer Völker. Daß er dabei manchmal
seinen bis- herigen Lebensraum verläßt ... die mißbrauchten Gastvölker erfährt."  >Among the
Jews, however, this attitude does not exist at all, for he was never a nomad, but always
only a parasite in the bodies of other peoples. The fact is that sometimes his habitat does
not depend on his intention but is the result of the expulsion, from time to time due to the
abused peoples experiences.

"Sie muß dann, ohne Rücksicht auf „Traditionen" und Vorurteile, den Mut finden, unser Volk
und seine Kraft zu sammeln zum Vormarsch auf jener Straße, die aus der heutigen Beengtheit
des Lebensraumes dieses Volk hinausführt zu neuem Grund und Boden und damit auch für immer
von der Gefahr befreit, auf dieser Erde zu vergehen oder als Sklavenvolk die Dienste anderer
besorgen zu müssen."  >It must then, without regard for traditions and prejudices, find the
courage, to gather our people and their strength, to take the road that emerges from the
today's constriction of the habitat this nation leads, to a new ground and soil and thus
also forever from the danger freed on this earth or as slaves to the services of others.

"So wie Deutschlands Grenzen Grenzen des Zufalls sind und Augenblicksgrenzen im jeweiligen
politischen Ringen der Zeit, so auch die Grenzen der Lebensräume der anderen Völker."  >Just
as Germany's borders are limits of chance, and momentary limits in the respective political
domain, the limits of habitats are based on the limits of their peoples.

"Sie kann und wird nur Sinn erhalten, wenn sie die Rückendeckung bietet für eine
Vergrößerung des Lebensraumes unseres Volkes in Europa."  >It can and will only sense if it
provides the back cover for an enlargement of the living space of our people in Europe.

*We see the group most mentioned in conjunction with "Lebensraum" are Jews not Slavs.


卐 - CHRISTIANITY IN THE THIRD REICH
------------------------------------
>Christianity is the basis of the entire morality of Germany http://youtu.be/KCwG13K7TAo
>Hitler will never forsake God http://youtu.be/MV1sVDU9E2E >Hitler defending Christianity
http://youtu.be/Sz42hBg4jys >Christianity and religion in Hitler's Germany
http://youtu.be/vat2wprB-0U >Debunking the anti-Christian myth
http://nobeliefs.com/HitlerSources.htm >Christianity is not Jewish
http://pastebin.com/9cxmXPCB >Adolf Hitler and Christianity
http://en.metapedia.org/wiki/Adolf_Hitler_and_Christianity >Debunking the Myths of "Nazi
Occultism"
http://web.archive.org/web/20160104235914/http://justice4germans.com/2013/08/07/debunking-the-myths-of-nazi-occultism-national-socialism-was-christian/
>Hitler and Christianity
http://mk.christogenea.org/podcasts/hitler-and-christianity-part-one
http://mk.christogenea.org/podcasts/hitler-and-christianity-part-two
http://mk.christogenea.org/podcasts/hitler-and-christianity-part-three-hitler-grant-stoddard
>Hitler and Christianity - Smoloko http://smoloko.com/?p=12985 >Was Catholic Hitler
"Anti-Christian"?  http://harrington-sites.com/Carrier5.htm >Positive Christianity in the
Third Reich - D. Cajus Fabricius
http://balderexlibris.com/index.php?post/Fabricius-D-Cajus-Positive-Christianity-in-the-third-Reich
>Positive Christianity in the Third Reich
http://christogenea.org/podcasts/positive-christianity-third-reich-part-1
http://christogenea.org/podcasts/positive-christianity-third-reich-part-2
http://christogenea.org/podcasts/positive-christianity-third-reich-part-3
http://christogenea.org/podcasts/positive-christianity-third-reich-part-4
http://christogenea.org/podcasts/positive-christianity-third-reich-part-5
http://christogenea.org/podcasts/positive-christianity-third-reich-part-6
http://christogenea.org/podcasts/positive-christianity-third-reich-part-7-final


卐 - NEO-PAGANISM ==================

>The Asatru Edda https://archive.org/details/TheAsatruEddaSacredLoreOfTheNorth

>Serrano: Temple of Wotan
https://archive.org/details/SerranoMiguelTempleOfWotanHolyBookOfTheAryanTribes20170324

>The Origin of Himmler's Spirituality: Waralda and the Oera Linda codex
http://fryskednis.blogspot.com/2014/12/himmler-referring-to-wralda.html

>The Wotan Network https://www.youtube.com/user/smcnallen

>The Asatru Folk Assembly http://www.runestone.org/

>Hans Jost: Path of Wotan https://archive.org/details/PathOfWotanByJost >David Lane: Creed
of Iron https://archive.org/details/CreedOfIron_501


卐 - ESOTERICISM ==================

>Miguel Serrano: Hitler, the ultimate avatar
http://aryanism.net/wp-content/uploads/Adolf-Hitler-The-Ultimate-Avatar-Part-One.pdf
http://aryanism.net/wp-content/uploads/Adolf-Hitler-The-Ultimate-Avatar-Part-Two.pdf

>Savitri Devi - Gold in the Furnace http://archive.org/details/GoldInTheFurnace_314 >Savitri
Devi - Impeachment of Man http://archive.org/details/impeachment-of-man-savitri-devi
>Savitri Devi - Defiance http://archive.org/details/Defiance_63

>Omniphi: Carl Jung, the Collective Unconscious https://youtu.be/Ivk_MM1OGZY >Omniphi:
Esoteric Kekism https://youtu.be/2ZPSnkQWs6o

>Jesus is NOT JEWISH MESSIAH, didn't match the Mashiach at all
http://www.jewfaq.org/mashiach.htm

>Christianity as a Roman re-branding of Aryan Theism https://youtu.be/HS0WSEuousE >Mythicist
positions: >Jesus Christ: A Pagan Myth by Laurence E. Dalton
https://archive.org/details/JNVVol1Archive >The World's 16 Crucified Saviors
https://archive.org/details/TheWorlds16CrucifiedSaviors_86 >Pagan Christs: studies in
comparative hierology https://archive.org/details/paganchristsstud00robe
http://churchandstate.org.uk/2016/05/demolishing-the-historicity-of-jesus-a-history/
http://hubpages.com/religion-philosophy/forum/42035/the-parallels-between-jesus-and-horus-

>Sven Longshanks' series on Aryan Esotericism (takes a more Christian-Centric view)
Playlist: >1 - Aryan Esoterica: Odin, the Runes, Gnosticism and Christ
https://archive.org/download/AE010517/AE%20010517.mp3 >2- Aryan Esoterica: Lucifer, the
Black Sun, Angels and the Green Thunderbolt
https://archive.org/download/AE011217/AE%20011217.mp3 >3- Aryan Esoterica: Archetypes,
Avatars, Hitler and Sex https://archive.org/download/AE011917/AE%20011917.mp3 >4 - Aryan
Esoterica: Jews, Judeans and Josephites
https://archive.org/download/AE012617/AE%20012617.mp3 >5 - Aryan Esoterica: In The Beginning
https://archive.org/download/AE020217/AE%20020217.mp3


卐 - BOOKS (1)
------
>Oswald Spengler - Prussianism and Socialism https://archive.is/Kt6UF >Alfred Rosenberg's
Criticism of Spengler
https://archive.org/download/AlfredRosenbergsCriticismOfOswaldSpengler/RosenbergCriticismOfSpengler.pdf
>Karl Marx - A Critique of the German Ideology
https://www.marxists.org/archive/marx/works/download/Marx_The_German_Ideology.pdf >Martin
Heidegger - Ponderings Books II–VI
https://archive.org/details/martin-heidegger-ponderings-iivi-black-notebooks-1931-1938
>Adolf Hitler - Mein Kampf (English) Ford:
http://nationalactionlondon.files.wordpress.com/2015/06/adolf-hitler-mein-kampf-ford-translation.pdf
Stalag: http://endchan.xyz/.media/a18332e643d7cb83515627b693496fc0-applicationpdf Kindle:
http://my.mixtape.moe/ktzprb.azw3 EPUB: http://my.mixtape.moe/uucnjk.epub >Adolf Hitler -
Mein Kampf (Deutsch) http://archive.org/details/Hitler-Adolf-Mein-Kampf >Adolf Hitler - The
Words of Adolf Hitler http://archive.org/details/WordsOfHitler_201307 >Adolf Ehrt -
Communism in Germany http://archive.org/details/CommunismInGermany >Gottfried Feder - The
Program Of The NSDAP The National Socialist Workers' Party And Its General Conceptions
http://archive.org/details/GottfriedFeder_TheProgramOfTheNSDAP >Gottfried Feder - Das
Programm der NSDAP (Deutsch)
http://archive.org/details/Feder-Gottfried-Das-Programm-der-NSDAP >Gottfried Feder -
Manifesto For The Abolition Of Interest Slavery
http://archive.org/details/GottfriedFederManifestoForTheAbolitionOfInterestSlavery1919
>Gottfried Feder The German State On A National And Socialist Foundation
http://archive.org/details/GottfriedFederTheGermanStateOnANationalAndSocialistFoundation
>James Mason - 'Siege'
http://laraj.ca/AGwiki/uploads/Fascism/America/James%20Mason%20-%20Siege.pdf >ORIGINAL
National Socialist speeches and essays (archives)
http://research.calvin.edu/german-propaganda-archive/pre1933.htm
http://research.calvin.edu/german-propaganda-archive/ww2era.htm#Material

卐 - BOOKS (2)
------
Pamphlets published in English by the NSDAP explaining aspects of the German system.
>Social Welfare in Germany: https://archive.org/details/SocialWelfareInGermany >German Youth
in a Changing World: https://archive.org/details/GermanYouthInAChangingWorld >German
Economic Policy: https://archive.org/details/GermanEconomicPolcy >German Law and
Legislation: https://archive.org/details/GermanLawAndLegislation >German Education Today:
https://archive.org/details/GermanEducationToday >German Labour Service:
https://archive.org/details/FermanLabourServise >The New Order - Collateral Reading
http://pastebin.com/za2P7xX9 >Tomislav Sunic - Art in the Third Reich: 1933-1945
http://archive.org/details/ArtInTheThirdReich19331945 >The Triumph of Reason - The Thinking
Man's Adolf Hitler by Michael Walsh
http://archive.org/details/TheTriumphOfReason-TheThinkingMansAdolfHitler >Leon Degrelle -
Campaign in Russia: the Waffen SS on the Eastern Front
http://germanvictims.com/wp-content/uploads/2013/07/Campaign-in-Russia-Leon-Degrelle.pdf

卐 - BOOKS (3)
------
>The Works of David Irving http://pastebin.com/FZ0cg8gB >James Bacque - Other Losses
http://archive.org/details/OtherLosses_201608 >James Bacque - Crimes and Mercies
http://archive.org/details/CrimesAndMerciesByJamesBacque1997 >Savitri Devi - Gold in the
Furnace http://archive.org/details/GoldInTheFurnace_314 >Savitri Devi - Impeachment of Man
http://archive.org/details/impeachment-of-man-savitri-devi >Savitri Devi - Defiance
http://archive.org/details/Defiance_63 >Maurice Samuels - You Gentiles
http://archive.org/details/YouGentiles_414 >Henry Ford - The International Jew
http://archive.org/details/TheInternationalJewByHenryFord1920 >Wayne MacLeod - The
Importance of Race in Civilization
http://archive.org/details/TheImportanceOfRaceInCivilization >Israel Shahak - Jewish
History, Jewish Religion: The Weight of 3,000 Years
http://archive.org/details/JewishHistoryJewishReligionTheWeightOf3000Years-I.Shahak >Matt
Koehl - The Revolutionary Nature of National Socialism
http://theneworder.org/national-socialism/idea-movement/the-revolutionary-nature-of-national-socialism/
>Colin Jordan - National Socialism: Vanguard of the Future
http://archive.org/details/NationalSocialismVanguardOfTheFutureSelectedWritingsOfColinJordan
>Kevin MacDonald - Cultural Insurrections: Essays on Western Civilization, Jewish Influence
and Anti-Semitism http://toqonline.com/bookstore/insurrections/ >Kevin MacDonald - The
Culture of Critique http://angelfire.com/rebellion2/goyim/je1.pdf


卐 - HOLOHOAX
-------------
>Pastebins http://pastebin.com/35E6BdQ4 http://pastebin.com/Uc1EkvGZ >Holocaust forensics
handbooks series http://holocausthandbooks.com/dl/HHS-pdf.zip Kindle:
http://holocausthandbooks.com/dl/HHS-kindle.zip >Harold Covington: Common questions and
answers https://youtu.be/zeqsiR4HVCA >Germar Rudolf exposes Auschwitz's Curated Lies
https://youtu.be/PSYJBVvyP08 >The First Holocaust : The Surprising Origin of the Six-Million
Figure https://youtu.be/yBnMtkbWPCs >Eric Hunt: Treblinka, Belzec, Sobibor
http://youtu.be/7dxsVSzL4HE >David Cole http://youtu.be/Os0eldMv-wE
http://youtu.be/RHzWo79dCHs http://youtu.be/QxAvpvz_4wQ >David Irving
http://youtu.be/MLloM6ufVgk >Gerd Shulze-Ronhoff http://youtu.be/MejbBsSAP8I >Steven
Anderson http://youtu.be/rhGMCYWqKI >The Haavara Agreement https://youtu.be/zE_daetNn8s
https://youtu.be/VBLiohokieI http://youtu.be/j-1ts3VTeeI >The 6 million “You shall return
minus 6 million" http://youtu.be/LjRsoLqHGr4


卐 - PASTEBINS
--------------
>Redpills of Zion http://pastebin.com/MSvkCCRy >The Jews http://pastebin.com/TzZC78cp >The
Truth of Races http://pastebin.com/zapWyu7A >Holocaust Revisionism
http://pastebin.com/Uc1EkvGZ >Negroid facts http://pastebin.com/7wfQE5mD >Hitler was not a
Jew http://pastebin.com/Rbcx3psi >Christianity is not Jewish http://pastebin.com/9cxmXPCB
>NSG Reading Pastebin with Index http://pastebin.com/BUU4tbiw


卐 - RACE MIXING AND WHY IT'S BAD
---------------------------------
http://pastebin.com/tGMEhbhf http://msu.edu/~renn/RHE-_mixed_race.pdf
http://ncbi.nlm.nih.gov/pmc/articles/PMC1448064/
http://content.time.com/time/health/article/0,8599,1993074,00.html
http://sociobiologicalmusings.blogspot.ca/2011/10/problems-with-mixed-race-marriages-and.html
http://nature.com/scitable/topicpage/haldane-s-rule-the-heterogametic-sex-1144


卐 - BLACKS
-------------------
>We Thought They Were White http://archive.is/WEyhL >Pastor Ray Hagins on Adolf Hitler
http://youtu.be/hVBDXSWOJSM >Black people talk about Jews http://youtu.be/0QbjELF-8kY >Why
Idi Amin kicked out the Israelis http://youtu.be/jY_IASYZny4 >Dr. Tony Martin & David
Irving - The Jewish Role in the African Slave Trade
http://youtube.com/watch?v=vAb4DLVZOW8&feature=youtu.be >Highlights and Key Points from: The
Secret Relationship Between Blacks and Jews
http://noirg.org/wp-content/uploads/2012/04/TSR.HighlightsKeyPoints1.pdf >The Secret
Relationship Between Blacks and Jews: Volume One
https://www.radioislam.org/islam/english/books/secrrel1/The%20Secret%20Relationship%20between%20Blacks%20and%20Jews.pdf
>The Secret Relationship Between Blacks and Jews: Volume Two
http://vho.org/aaargh/fran/livres10/SR2sample.pdf >Blacks supporting Hitler
http://youtube.com/watch?v=xGyJrMdwDv4&feature=youtu.be


卐 - ANTHEMS/TRIBUTES
---------------------
>Germany (Horst Wessel Lied) http://youtu.be/3mp4aOABbsI >Russian Liberation Army
http://youtu.be/ofgLFvFDjKg >Sieg Heil Viktoria (Schutzstaffel und Waffen-SS)
http://youtu.be/wO9DuKbnOmQ >Netherlands http://youtu.be/GelHmi1ec8k >Serbia
http://youtu.be/-P8RbKAsVss >Sweden http://youtu.be/7cH_XrmHE0I >Flanders/Belgium
http://youtu.be/oFbJyf-_tVk >Slovakia http://youtu.be/dUPXTAG1Bvk >Bosnia
http://youtu.be/A8N2W74AULc >Ukraine http://youtu.be/oxPvRdqkX9g >Bulgaria
http://youtu.be/1tFeT0F8SHA >Italy http://youtu.be/z2lNTdAiyWw >Croatia
http://youtu.be/orOsyDt_zR8&nohtml5 >Slovakia http://youtu.be/SFdulJcMMUE#t=83 >Hungary
http://youtu.be/HJd1T10kYv8 >Romania http://youtu.be/8Whdj1JRK6s >Japan
http://youtu.be/sd6YpZ-C9y0#t=12 >Falangist Spain http://youtu.be/_8-u6kiLCvE >British Union
of Fascists http://youtu.be/-9q-cjWPsDY >Finland http://youtu.be/_kLC0bXNE5I >Vichy France
http://youtu.be/D9XNzcqA42s >Metaxist Greece http://youtu.be/lyzKs-H8nJs >Rexist Belgium
http://youtu.be/A3TpEwRnlxg >Free Russia http://youtu.be/dYCZbkVVdFA >Verdinaso Belgium
http://youtu.be/zeRnUxH0BsA&nohtml5=False >Estado Novo (Portugal)
http://youtu.be/Dx_8Vzuyayg >Serbia ZBOR http://youtu.be/ouURJ1-krqk >Poland
http://youtu.be/24lv8pVXWDg >Silver Legion of America http://youtu.be/I220nSDnDPs >Brazil
http://youtu.be/wg5v97PyIEo


卐 - WEBMS:
---------------------------
https://a.pomf.cat/fsvxtb.webm https://a.pomf.cat/wvrcgy.webm https://a.pomf.cat/rmdecl.webm
https://a.pomf.cat/scdtdb.webm https://a.pomf.cat/juomhh.webm https://a.pomf.cat/dqmflv.webm
https://a.pomf.cat/ihzllw.webm https://a.pomf.cat/wupkzm.webm https://a.pomf.cat/bfofwj.webm
https://a.pomf.cat/yktzbk.webm https://a.pomf.cat/zghabz.webm https://a.pomf.cat/pptwlw.webm
https://a.pomf.cat/jjymgk.webm https://a.pomf.cat/vjmuhl.webm https://a.pomf.cat/ijhodj.webm
https://a.pomf.cat/eraulm.webm https://a.pomf.cat/aberbn.webm


卐 - FASCIST/NATSOC MOVIES:
---------------------------
The following link contains 26 Third Reich movies (One from fascist Italy, one from occupied
France).  All are good quality DVDRIP (x265 codec) and all have English subtitles.

> https://mega.nz/#F!F99QQIxC!0aljCC-AfqqhAX48T_U78g

List and genre: >Bismarck 1940 Biopic, Historical >Condottieri 1937 Historical, Adventure
(Fascist Italy) >Das Herz Der Königin (The Heart of the Queen) 1940 Anti-British, historical
>Der große König (The Great King) 1942 Biopic, historical >Der Kaiser von Kalifornien (The
Emperor of California) 1936 Anti-greed, historical >Der Sieg Des Glaubens (The Triumpth of
the Faith) 1933 NSDAP propaganda

Full list here: >http://pastebin.com/dvzfs5tM


卐 - FALANGIST ============== >Spanish Falangist Source Documents in English by Jose Antonio
Primo De Rivera, Ernesto Gimenez Caballero
http://archive.org/details/SpanishFalangistEnglishSources >Twenty-Six Point Program of the
Falange by Jose Antonio Primo de Rivera
http://archive.org/details/Twenty-sixPointProgramOfTheFalange >Jose Antonio and The Spanish
Falange http://archive.org/details/JoseAntonioAndTheSpanishFalange >For My Legionaries -
Codreanu http://archive.org/details/ForMyLegionaries


卐 - TRADITIONALIST =================== >Leszek Kołakowski http://youtu.be/oZtJP7M-9Og >A
challenge to conservatism
http://archive.org/details/TheSocialDemocraticChallengeAResponseToConservatism >Left and
Right http://archive.org/details/ConceptOfLeftAndRight >Nicolás Gómez Dávila
http://genius.com/Nicolas-gomez-davila-selected-aphorisms-part-i-annotated
http://genius.com/Nicolas-gomez-davila-selected-aphorisms-part-2-annotated >Mircea Eliade
http://youtu.be/6v8Kf6vYYeY


卐 - A TIME WHEN PEOPLE WERE HAPPY
----------------------------------
http://youtu.be/cfNQaE-FPwU http://youtu.be/_7vVst4qpKg   http://youtu.be/7wU2m064iaQ
http://youtu.be/RPh6yJoyZbk http://youtu.be/AOBXc5exrL8


Christmas: >Winterhilfswerk http://youtu.be/FiIE6PSTA5M >The Winter Help Organization -
Chapter from "The Case for Germany" (1938)
http://wintersonnenwende.com/scriptorium/english/archives/caseforgermany/cfg13.html
>Christmas in the Reich - Hitler spending the holiday with close friends, Goebbels handing
out presents, Goering dressed up as Santa. Good times.  http://youtu.be/RMT74PZTtiU >Living
in Hitler's Germany: a letter from Hans Schmidt: http://youtu.be/kdIb0ElUpG0
http://archive.org/stream/SchmidtLifeInHitlersGermany/Schmidt-LifeInHitlersGermany_djvu.txt

================================卐 - MYTHS ABOUT NATSOC (Part 1) >"National Socialism is
just (((socialism)))"

Marxist (Left) socialism and National (Right) Socialism are "antipodal zeitgeists engaged in
dialectic". That's a fancy way to say they're opposite ideologies designed to clash, like
Yin and Yang.

NatSoc was fundamentally an ideology built around race, while Marxist socialism was entirely
different: built around class. Hitler aimed to unite the right and left, including workers
and their bosses, into a new German nation based on racial identity. Socialism, in contrast,
was a class war between workers, bosses, and owners (Capitalists), aiming to build a workers
state in which race and gender were insignificant. Socialists, especially Marxist
socialists, were anti-religious atheists, whereas NatSoc went so far as to make Christianity
the religion of the state.

The differences go on and on: Marxist socialism was internationalist, NatSoc was
nationalist. Marxist socialism was egalitarian, whereas NatSoc believed that nature was
unequal and required competition. Marxist socialism wanted to nationalize all private
industry, while NatSoc privatized every major industry except the railroads (it considered
these a military asset). In fact, Hitler once joked "they didn't need to nationalize
property because they nationalized people". NatSoc drew on a range of pan-German theories,
which wanted to blend Aryan workers and Aryan magnates into a super Aryan state, which would
involve the eradication of class-focused socialism as a non-German ideology.

================================卐 - MYTHS ABOUT NATSOC (Part 2) >"National Socialism is
just (((socialism)))"

NatSoc redefined socialism as "Germanism/Volkism", which they saw as "producer-oriented
capitalism", as opposed to "Jewish capitalism", aka, international finance, globalism, wall
street, etc. In theory, NatSoc economics was a version of Keynesianism, tailored to the
Völkisch nature of whichever people adopted it. Its not one dogmatic economic system,and
Hitler often joked that the lack of a specific ideology was their strength. NatSoc could be
more "free market" as Americans know it, or less. But NatSoc is always in favor of the Volk
over economic identity, of "producer capitalism" over "finance capitalism".

Hitler tried to clarify the distinction in 1938: >“’Socialist’ I define from the word
‘social’ meaning in the main ‘social equity’. A Socialist is one who serves the common good
without giving up his individuality or personality or the product of his personal
efficiency.  >Our adopted term ‘Socialist has nothing to do with Marxian Socialism.
((((Marxism))) is anti-property; true socialism is not. ((((Marxism))) places no value on
the individual, or individual effort, of efficiency; true Socialism values the individual
and encourages him in individual efficiency, at the same time holding that his interests as
an individual must be in consonance with those of the community. All great inventions,
discoveries, achievements were first the product of an individual brain. It is charged
against me that I am against property, that I am an atheist. Both charges are false.”

See also:

>Private property in the industry of the Third Reich is often considered a mere nominal
provision without much substance. However, that is not correct, because firms, despite the
rationing and licensing activities of the state, still had ample scope to devise their own
production and investment profiles. Even regarding war-related projects, freedom of contract
was generally respected; instead of using power, the state offered firms a number of
contract options to choose from. There were several motives behind this attitude of the
regime, among them the conviction that private property provided important incentives for
increasing efficiency.

https://www.cambridge.org/core/journals/journal-of-economic-history/article/div-classtitlethe-role-of-private-property-in-the-nazi-economy-the-case-of-industrydiv/5853885D956348A13B5CEFDC42313E2B

>Against the Mainstream: Nazi privatization in 1930's Germany (Germa Bel)
http://www.ub.edu/graap/EHR.pdf
http://voxeu.org/article/macroeconomics-germany-forgotten-lesson-hjalmar-schacht
https://pridecomethbeforeafall.wordpress.com/2014/02/10/hitlers-economic-miracle/
https://youtu.be/pKnFN8P21-0

================================卐 - MYTHS ABOUT NATSOC (Part 3) >"National Socialism /
Fascism was a failed system"

It's intellectually dishonest to label something that was forcibly crushed a "failed
system", implying that a nation bombed into collapse during war is comparable to a system
imploding politically during peace-time. The Soviet system failed, as did the Roman Empire,
and every Chinese or Ottoman dynasty. Some of these examples of government lasted thousands
of years, while some didn't last more than a generation. All forms of government inevitably
fail. This has been true since ancient times. Polybius famously articulated this process of
Anacyclosis: social organization paradigms rise, fail, and give way to further systems. This
is the cycle of history.

Fascism is not a failed system, it was a defeated system: A.) it was not an economic system,
but a social one; B.) the so-called "failed system" had a control group: the US. Germany,
Italy, and the US were operating under Keynesean policies; only one of them won the war, and
experienced a massive period of growth once their industrial rivals were destroyed. So no,
it wasn't a failed system, because both sides were using it, including the side that won.

https://mises.org/library/three-new-deals-why-nazis-and-fascists-loved-fdr
