* Obama and Dirty War in Argentina
  :PROPERTIES:
  :CUSTOM_ID: copy-of-obama-and-dirty-war-in-argentina
  :END:
Last March, when President Obama travelled to Argentina to meet with the
country's new President, Mauricio Macri, his public appearances were
dogged by protesters who noisily demanded explanations, and apologies,
for U.S. policies, past and present. There are few countries in the West
where anti-Americanism is as vociferously expressed as in Argentina,
where a highly politicized culture of grievance has evolved in which
many of the country's problems are blamed on the United States. On the
left, especially, there is lingering resentment over the support
extended by the U.S. government to Argentina's right-wing military,
which seized power in March of 1976 and launched a "Dirty War" against
leftists that took thousands of lives over the following seven years.

Obama's visit coincided with the fortieth anniversary of the coup. He
pointedly paid homage to the Dirty War's victims by visiting a shrine
built in their honor on the outskirts of Buenos Aires. In an address he
gave at the shrine, Obama acknowledged what he characterized as American
sins of omission, but he stopped short of issuing an outright apology.
"Democracies have to have the courage to acknowledge when we don't live
up to the ideals that we stand for," he said. "And we've been slow to
speak out for human rights, and that was the case here."
