* Uthnw Egypt
  :PROPERTIES:
  :CUSTOM_ID: copy-of-uthnw-egypt
  :END:
التقرير دا من السنة الي فاتت, إسمه wealth report بتعمله knight frank كل
سنة، الجزء الي الجزيرة - صحف أخرى آز ويل - وهو نفس الجزء في الصورة،
بيتكلم عن الـUltra high-net-worth individual، أحد كبرى آفات الرأسمالية..
التقرير بتاع knight frank مش مصدر كويس فعلًا وأبعد ما يكون عن abstracted
paper تستدل بيها على شيء (بيتكلم عن أكتر من 100 دولة، مش بيدي أي تفاصيل
عن منين جاب المعلومات دي أو درسها إزاي)، لكن المعلومة الي قالها مش
محتاجة إعادة نَظر حتى، خصوصًا في نقطة الهند.

[[https://content.knightfrank.com/content/pdfs/global/the-wealth-report-2020.pdf?fbclid=IwAR1ZG_ZivfXpQSk3FytVSOZdop5c04otZriqjGBS9etRluB99fFvQ7s29Js][https://content.knightfrank.com/.../the-wealth-report...]]

لكن بخصوص مصر, في 2012 الglobal team ف wealth-x (ودي تعتبر مَصدر بحثي
أكتر من knight frank الي معمولة علشان الاهتمامات العقارية أصلًا)، نشرت
تقرير بتقول فيه إن الـUHNWI في مصر وصل لـ490 فرد معاهم ~65 مليار دولار،
ودا كان رقم كبير بالنسبة لدولة زي مصر.

[[https://www.wealthx.com/about-us/press-news/company-news/2012/egypt-home-to-490-ultra-rich-individuals-report/?fbclid=IwAR2zh18iylfx7ElUfUYBCjg0Czrk8Y1bW-3ocSlyHi7Rwe5kuuFWFsrvjMk][https://www.wealthx.com/.../egypt-home-to-490-ultra-rich.../]]3

في 2017، الـAfrAsia Bank Africa Wealth Report وجد إن مصر عندها تاني أكبر
نسبة مليونيرات في أفريقيا كلها، بعدد قدره 8,900 مليونير (طبعًا مش كل
مليونير بيتحط في الـuhnwi، بياخدوا فقط الأكبر من 20 مليون)، كنا تاني
دولة مباشرة بعد جنوب أفريقيا. و
[[https://www.afrasiabank.com/.../africa-wealth-report-2017][https://www.afrasiabank.com/.../africa-wealth-report-2017]]...
بعد 3 سنين في 2020 نفس التقرير من الـABA بيقول إن العدد دا بقى 15,500
(في الصفحة السادسة من التقرير)
[[https://e.issuu.com/embed.html?u=newworldwealth&d=africa_2021&fbclid=IwAR1CXURIaqheC5S_T6SmXY-plykjBETWT-oT0vj0itcZyZ10Zb1gFcfmPFk][https://e.issuu.com/embed.html?u=newworldwealth...]]
يعني 160% زيادة عن السنة الي فاتت. والـmulti-millionaires (ودول الي
عندهم 10 مليون وفوق، يعني رقم قريب من الـuhnwi) زادوا واصبحوا 810، أه
نسيت أقول إن الرقم دا كان 480 في تقرير 2017، يعني زيادة ضعف تقريبًا، دول
يعتبروا الاثرياء الصغار الي مش داخلين جوا الuhnwi.. تقدر تتخيل الي جواها
زادوا بقدر قد إيه. دا كله بدون المساس بتقرير الـknight frank لـ2021 الي
أتمنى من كل قلبي فعلًا إن عدم ثقتي فيه تكون في محلها else، المصيبة أكبر
مما نتخيل فعلًا
